services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - VUE_APP_SUBDOMAIN=dzaky
      - PORT=3000
      - NAME=dzaky
    volumes:
      - .:/app
